services:
  mongodb:
    image: mongo:8
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - docflow-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage
    # environment:
    #   - LLM_PROVIDER=${LLM_PROVIDER:-groq}
    #   - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
    #   - STORAGE_BASE_PATH=/app/storage
    #   - GROQ_API_KEY=${GROQ_API_KEY}
    #   - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
    #   - MONGODB_DB_NAME=${MONGODB_DB_NAME:-docflow}
    networks:
      - docflow-net
    # Permet au conteneur de communiquer avec Ollama sur l'hote Mac/Windows
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/ # Utilise le proxy Nginx configure
    depends_on:
      - backend
    networks:
      - docflow-net

  airflow:
    image: apache/airflow:2.8.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _PIP_ADDITIONAL_REQUIREMENTS=reportlab<4.0.0 requests
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test_documents:/opt/airflow/test_documents
    user: "${AIRFLOW_UID:-50000}:0"
    command: bash -c "airflow db init && airflow standalone"
    networks:
      - docflow-net

networks:
  docflow-net:
    driver: bridge

volumes:
  mongodb-data:
